/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.emm.premaintain;

import nc.vo.am.common.AMSuperVO;
import nc.vo.pub.lang.UFBoolean;
import nc.vo.pub.lang.UFDate;

/**
 * <b> 预防性维护的表头VO </b>
 * <p>
 * 时间型，绩效型和条件型的预防性维护使用
 * </p>
 * 创建日期:2009-12-01 19:14:14
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PMHeadVO extends AMSuperVO {
	/** 主键 */
	private java.lang.String pk_pm;
	/** 集团 */
	private java.lang.String pk_group;
	/** 维修组织 */
	private java.lang.String pk_org;
	/** 维修组织版本 */
	private java.lang.String pk_org_v;
	/** 单据状态 */
	private java.lang.Integer bill_status;
	/** 单据类型 */
	private java.lang.String bill_type;
	/** 交易类型 */
	private java.lang.String transi_type;
	private java.lang.String pk_transitype;
	/** 业务类型 */
	private java.lang.String busi_type;
	/** 单据编码 */
	private java.lang.String bill_code;
	/** 预防性维护内容 */
	private java.lang.String content;
	/** 设备 */
	private java.lang.String pk_equip;
	/** 位置 */
	private java.lang.String pk_location;
	/** 封存 */
	private java.lang.Integer enablestate = 2;
	/** 工作类型 */
	private java.lang.String pk_worktype;
	/** 工单状态 */
	private java.lang.String pk_wo_status;
	/** 工单优先级 */
	private java.lang.String pk_priority;
	/** 优先级理由 */
	private java.lang.String pri_clause;
	/** 工单执行人 */
	private java.lang.String pk_executor;
	/** 工单主管人 */
	private java.lang.String pk_director;
	/** 工作班组 */
	private java.lang.String pk_psn_group;
	/** 负责专业 */
	private java.lang.String pk_specialty;
	/** 负责部门 */
	private java.lang.String pk_wo_dept;
	/** 负责部门版本 */
	private java.lang.String pk_wo_dept_v;
	/** 检修路线 */
	private java.lang.String pk_inspection_road;
	/** 计数器 */
	private java.lang.Integer counter;
	/** 下一工作包 */
	private java.lang.String next_std_job;
	/** 首次开始日期 */
	private nc.vo.pub.lang.UFDate initial_date;
	/** 生成周期 */
	private java.lang.Integer periods;
	/** 周期单位 */
	private java.lang.Integer periods_unit = 0;
	/** 提前天数 */
	private java.lang.Integer ahead_days = 0;
	/** 可变计划 */
	private nc.vo.pub.lang.UFBoolean alter_flag = UFBoolean.FALSE;
	/** 上一工单目标日期 */
	private nc.vo.pub.lang.UFDate pre_start_date;
	/** 上一工单完成日期 */
	private nc.vo.pub.lang.UFDate pre_end_date;
	/** 下一工单目标日期 */
	private nc.vo.pub.lang.UFDate next_start_date;
	/** 调整后目标日期 */
	private nc.vo.pub.lang.UFDate adjust_start_date;
	/** 永久调整 */
	private nc.vo.pub.lang.UFBoolean persist_flag = UFBoolean.FALSE;
	/** 调整人 */
	private java.lang.String pk_adjuster;
	/** 调整日期 */
	private nc.vo.pub.lang.UFDateTime adjust_date;
	/** 最新生成单据主键 */
	private java.lang.String pk_pre_bill;
	/** 项目 */
	private String pk_project;
	
	/** 制单人 */
	private java.lang.String billmaker;
	/** 制单时间 */
	private nc.vo.pub.lang.UFDateTime billmaketime;
	
	/** 创建人 */
	private java.lang.String creator;
	/** 创建时间 */
	private nc.vo.pub.lang.UFDateTime creationtime;
	/** 修改人 */
	private java.lang.String modifier;
	/** 修改日期 */
	private nc.vo.pub.lang.UFDateTime modifiedtime;
	/** 审核人 */
	private java.lang.String auditor;
	/** 审核日期 */
	private nc.vo.pub.lang.UFDateTime audittime;
	/** 审核意见 */
	private java.lang.String check_opinion;
	// 下一工单生成日期
	private nc.vo.pub.lang.UFDate next_create_date;

	/** 自定义项 */
	private java.lang.String def1;
	private java.lang.String def2;
	private java.lang.String def3;
	private java.lang.String def4;
	private java.lang.String def5;
	private java.lang.String def6;
	private java.lang.String def7;
	private java.lang.String def8;
	private java.lang.String def9;
	private java.lang.String def10;
	private java.lang.String def11;
	private java.lang.String def12;
	private java.lang.String def13;
	private java.lang.String def14;
	private java.lang.String def15;
	private java.lang.String def16;
	private java.lang.String def17;
	private java.lang.String def18;
	private java.lang.String def19;
	private java.lang.String def20;

	/** 设备信息，需要工单重新查询最新的设备信息 */
	// private java.lang.String pk_ownerorg;
	// private java.lang.String pk_mandept;
	// private java.lang.String pk_manager;
	// private java.lang.String pk_usedunit;
	// private java.lang.String pk_usedorg;
	// private java.lang.String pk_usedept;
	// private java.lang.String pk_user;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_TRANSITYPE = "pk_transitype";
	public static final String PK_PM = "pk_pm";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String BILL_STATUS = "bill_status";
	public static final String BILL_TYPE = "bill_type";
	public static final String TRANSI_TYPE = "transi_type";
	public static final String BUSI_TYPE = "busi_type";
	public static final String BILL_CODE = "bill_code";
	public static final String CONTENT = "content";
	public static final String PK_EQUIP = "pk_equip";
	public static final String PK_LOCATION = "pk_location";
	public static final String ENABLESTATE = "enablestate";	
	public static final String PK_WORKTYPE = "pk_worktype";
	public static final String PK_WO_STATUS = "pk_wo_status";
	public static final String PK_PRIORITY = "pk_priority";
	public static final String PRI_CLAUSE = "pri_clause";
	public static final String PK_EXECUTOR = "pk_executor";
	public static final String PK_DIRECTOR = "pk_director";
	public static final String PK_PSN_GROUP = "pk_psn_group";
	public static final String PK_SPECIALTY = "pk_specialty";
	public static final String PK_WO_DEPT = "pk_wo_dept";
	public static final String PK_WO_DEPT_V = "pk_wo_dept_v";
	public static final String PK_INSPECTION_ROAD = "pk_inspection_road";
	public static final String COUNTER = "counter";
	public static final String NEXT_STD_JOB = "next_std_job";
	public static final String INITIAL_DATE = "initial_date";
	public static final String PERIODS = "periods";
	public static final String PERIODS_UNIT = "periods_unit";
	public static final String AHEAD_DAYS = "ahead_days";
	public static final String ALTER_FLAG = "alter_flag";
	public static final String PRE_START_DATE = "pre_start_date";
	public static final String PRE_END_DATE = "pre_end_date";
	public static final String NEXT_START_DATE = "next_start_date";
	public static final String ADJUST_START_DATE = "adjust_start_date";
	public static final String PERSIST_FLAG = "persist_flag";
	public static final String PK_ADJUSTER = "pk_adjuster";
	public static final String ADJUST_DATE = "adjust_date";
	public static final String PK_PRE_BILL = "pk_pre_bill";
	public static final String BILLMAKER = "billmaker";
	public static final String BILLMAKETIME = "billmaketime";
	public static final String CREATOR = "creator";
	public static final String CREATIONTIME = "creationtime";
	public static final String MODIFIER = "modifier";
	public static final String MODIFIEDTIME = "modifiedtime";
	public static final String AUDITOR = "auditor";
	public static final String AUDITTIME = "audittime";
	public static final String CHECK_OPINION = "check_opinion";
	public static final String DEF1 = "def1";
	public static final String DEF2 = "def2";
	public static final String DEF3 = "def3";
	public static final String DEF4 = "def4";
	public static final String DEF5 = "def5";
	public static final String DEF6 = "def6";
	public static final String DEF7 = "def7";
	public static final String DEF8 = "def8";
	public static final String DEF9 = "def9";
	public static final String DEF10 = "def10";
	public static final String DEF11 = "def11";
	public static final String DEF12 = "def12";
	public static final String DEF13 = "def13";
	public static final String DEF14 = "def14";
	public static final String DEF15 = "def15";
	public static final String DEF16 = "def16";
	public static final String DEF17 = "def17";
	public static final String DEF18 = "def18";
	public static final String DEF19 = "def19";
	public static final String DEF20 = "def20";
	public static final String NEXT_CREATE_DATE = "next_create_date";

	// public static final String PK_OWNERORG = "pk_ownerorg";
	// public static final String PK_MANDEPT = "pk_mandept";
	// public static final String PK_MANAGER = "pk_manager";
	// public static final String PK_USEDUNIT = "pk_usedunit";
	// public static final String PK_USEDORG = "pk_usedorg";
	// public static final String PK_USEDEPT = "pk_usedept";
	// public static final String PK_USER = "pk_user";

	/**
	 * 属性pk_pm的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_pm() {
		return pk_pm;
	}

	/**
	 * 属性pk_pm的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_pm
	 *            java.lang.String
	 */
	public void setPk_pm(java.lang.String newPk_pm) {
		this.pk_pm = newPk_pm;
	}

	/**
	 * 属性pk_group的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group() {
		return pk_group;
	}

	/**
	 * 属性pk_group的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_group
	 *            java.lang.String
	 */
	public void setPk_group(java.lang.String newPk_group) {
		this.pk_group = newPk_group;
	}

	/**
	 * 属性pk_org的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org() {
		return pk_org;
	}

	/**
	 * 属性pk_org的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_org
	 *            java.lang.String
	 */
	public void setPk_org(java.lang.String newPk_org) {
		this.pk_org = newPk_org;
	}

	/**
	 * 属性pk_org_v的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org_v() {
		return pk_org_v;
	}

	/**
	 * 属性pk_org_v的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_org_v
	 *            java.lang.String
	 */
	public void setPk_org_v(java.lang.String newPk_org_v) {
		this.pk_org_v = newPk_org_v;
	}

	/**
	 * 属性bill_status的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getBill_status() {
		return bill_status;
	}

	/**
	 * 属性bill_status的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newBill_status
	 *            java.lang.Integer
	 */
	public void setBill_status(java.lang.Integer newBill_status) {
		this.bill_status = newBill_status;
	}

	/**
	 * 属性bill_type的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBill_type() {
		return bill_type;
	}

	/**
	 * 属性bill_type的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newBill_type
	 *            java.lang.String
	 */
	public void setBill_type(java.lang.String newBill_type) {
		this.bill_type = newBill_type;
	}

	/**
	 * 属性transi_type的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTransi_type() {
		return transi_type;
	}

	/**
	 * 属性transi_type的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newTransi_type
	 *            java.lang.String
	 */
	public void setTransi_type(java.lang.String newTransi_type) {
		this.transi_type = newTransi_type;
	}

	/**
	 * 属性busi_type的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.String getBusi_type() {
		return busi_type;
	}

	/**
	 * 属性busi_type的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newBusi_type
	 *            java.lang.Integer
	 */
	public void setBusi_type(java.lang.String newBusi_type) {
		this.busi_type = newBusi_type;
	}

	/**
	 * 属性bill_code的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBill_code() {
		return bill_code;
	}

	/**
	 * 属性bill_code的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newBill_code
	 *            java.lang.String
	 */
	public void setBill_code(java.lang.String newBill_code) {
		this.bill_code = newBill_code;
	}

	/**
	 * 属性content的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getContent() {
		return content;
	}

	/**
	 * 属性content的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newContent
	 *            java.lang.String
	 */
	public void setContent(java.lang.String newContent) {
		this.content = newContent;
	}

	/**
	 * 属性pk_equip的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_equip() {
		return pk_equip;
	}

	/**
	 * 属性pk_equip的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_equip
	 *            java.lang.String
	 */
	public void setPk_equip(java.lang.String newPk_equip) {
		this.pk_equip = newPk_equip;
	}

	/**
	 * 属性pk_location的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_location() {
		return pk_location;
	}

	/**
	 * 属性pk_location的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_location
	 *            java.lang.String
	 */
	public void setPk_location(java.lang.String newPk_location) {
		this.pk_location = newPk_location;
	}

	/**
	 * @return the enablestate
	 */
	public java.lang.Integer getEnablestate() {
		return enablestate;
	}

	/**
	 * @param enablestate
	 *            the enablestate to set
	 */
	public void setEnablestate(java.lang.Integer enablestate) {
		this.enablestate = enablestate;
	}
	

	/**
	 * 属性pk_worktype的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_worktype() {
		return pk_worktype;
	}

	/**
	 * 属性pk_worktype的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_worktype
	 *            java.lang.String
	 */
	public void setPk_worktype(java.lang.String newPk_worktype) {
		this.pk_worktype = newPk_worktype;
	}

	/**
	 * 属性pk_wo_status的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_wo_status() {
		return pk_wo_status;
	}

	/**
	 * 属性pk_wo_status的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_wo_status
	 *            java.lang.String
	 */
	public void setPk_wo_status(java.lang.String newPk_wo_status) {
		this.pk_wo_status = newPk_wo_status;
	}

	/**
	 * 属性pk_priority的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_priority() {
		return pk_priority;
	}

	/**
	 * 属性pk_priority的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_priority
	 *            java.lang.String
	 */
	public void setPk_priority(java.lang.String newPk_priority) {
		this.pk_priority = newPk_priority;
	}

	/**
	 * 属性pri_clause的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPri_clause() {
		return pri_clause;
	}

	/**
	 * 属性pri_clause的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPri_clause
	 *            java.lang.String
	 */
	public void setPri_clause(java.lang.String newPri_clause) {
		this.pri_clause = newPri_clause;
	}

	/**
	 * 属性pk_executor的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_executor() {
		return pk_executor;
	}

	/**
	 * 属性pk_executor的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_executor
	 *            java.lang.String
	 */
	public void setPk_executor(java.lang.String newPk_executor) {
		this.pk_executor = newPk_executor;
	}

	/**
	 * 属性pk_director的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_director() {
		return pk_director;
	}

	/**
	 * 属性pk_director的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_director
	 *            java.lang.String
	 */
	public void setPk_director(java.lang.String newPk_director) {
		this.pk_director = newPk_director;
	}

	/**
	 * 属性pk_psn_group的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_psn_group() {
		return pk_psn_group;
	}

	/**
	 * 属性pk_psn_group的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_psn_group
	 *            java.lang.String
	 */
	public void setPk_psn_group(java.lang.String newPk_psn_group) {
		this.pk_psn_group = newPk_psn_group;
	}

	/**
	 * 属性pk_specialty的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_specialty() {
		return pk_specialty;
	}

	/**
	 * 属性pk_specialty的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_specialty
	 *            java.lang.String
	 */
	public void setPk_specialty(java.lang.String newPk_specialty) {
		this.pk_specialty = newPk_specialty;
	}

	/**
	 * 属性counter的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getCounter() {
		return counter;
	}

	/**
	 * 属性counter的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newCounter
	 *            java.lang.Integer
	 */
	public void setCounter(java.lang.Integer newCounter) {
		this.counter = newCounter;
	}

	/**
	 * 属性next_std_job的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getNext_std_job() {
		return next_std_job;
	}

	/**
	 * 属性next_std_job的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newNext_std_job
	 *            java.lang.String
	 */
	public void setNext_std_job(java.lang.String newNext_std_job) {
		this.next_std_job = newNext_std_job;
	}

	/**
	 * 属性initial_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDate getInitial_date() {
		return initial_date;
	}

	/**
	 * 属性initial_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newInitial_date
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setInitial_date(nc.vo.pub.lang.UFDate newInitial_date) {
		this.initial_date = newInitial_date;
	}

	/**
	 * @return the periods
	 */
	public java.lang.Integer getPeriods() {
		return periods;
	}

	/**
	 * @param periods
	 *            the periods to set
	 */
	public void setPeriods(java.lang.Integer periods) {
		this.periods = periods;
	}

	/**
	 * @return the periods_unit
	 */
	public java.lang.Integer getPeriods_unit() {
		return periods_unit;
	}

	/**
	 * @param periods_unit
	 *            the periods_unit to set
	 */
	public void setPeriods_unit(java.lang.Integer periods_unit) {
		this.periods_unit = periods_unit;
	}

	/**
	 * 属性ahead_days的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getAhead_days() {
		return ahead_days;
	}

	/**
	 * 属性ahead_days的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAhead_days
	 *            java.lang.Integer
	 */
	public void setAhead_days(java.lang.Integer newAhead_days) {
		this.ahead_days = newAhead_days;
	}

	/**
	 * 属性alter_flag的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getAlter_flag() {
		return alter_flag;
	}

	/**
	 * 属性alter_flag的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAlter_flag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setAlter_flag(nc.vo.pub.lang.UFBoolean newAlter_flag) {
		this.alter_flag = newAlter_flag;
	}

	/**
	 * 属性pre_start_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getPre_start_date() {
		return pre_start_date;
	}

	/**
	 * 属性pre_start_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPre_start_date
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setPre_start_date(nc.vo.pub.lang.UFDate newPre_start_date) {
		this.pre_start_date = newPre_start_date;
	}

	/**
	 * 属性pre_end_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getPre_end_date() {
		return pre_end_date;
	}

	/**
	 * 属性pre_end_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPre_end_date
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setPre_end_date(nc.vo.pub.lang.UFDate newPre_end_date) {
		this.pre_end_date = newPre_end_date;
	}

	/**
	 * 属性next_start_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getNext_start_date() {
		return next_start_date;
	}

	/**
	 * 属性next_start_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newNext_start_date
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setNext_start_date(nc.vo.pub.lang.UFDate newNext_start_date) {
		this.next_start_date = newNext_start_date;
	}

	/**
	 * 属性adjust_start_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getAdjust_start_date() {
		return adjust_start_date;
	}

	/**
	 * 属性adjust_start_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAdjust_start_date
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setAdjust_start_date(nc.vo.pub.lang.UFDate newAdjust_start_date) {
		this.adjust_start_date = newAdjust_start_date;
	}

	/**
	 * 属性persist_flag的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getPersist_flag() {
		return persist_flag;
	}

	/**
	 * 属性persist_flag的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPersist_flag
	 *            nc.vo.pub.lang.UFBoolean
	 */
	public void setPersist_flag(nc.vo.pub.lang.UFBoolean newPersist_flag) {
		this.persist_flag = newPersist_flag;
	}

	/**
	 * 属性pk_adjuster的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_adjuster() {
		return pk_adjuster;
	}

	/**
	 * 属性pk_adjuster的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newPk_adjuster
	 *            java.lang.String
	 */
	public void setPk_adjuster(java.lang.String newPk_adjuster) {
		this.pk_adjuster = newPk_adjuster;
	}

	/**
	 * 属性adjust_date的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDateTime getAdjust_date() {
		return adjust_date;
	}

	/**
	 * 属性adjust_date的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAdjust_date
	 *            nc.vo.pub.lang.UFDate
	 */
	public void setAdjust_date(nc.vo.pub.lang.UFDateTime newAdjust_date) {
		this.adjust_date = newAdjust_date;
	}

	/**
	 * 属性pk_pre_bill的Getter方法.属性名：最新生成单据主键
	 * 创建日期:
	 * @return java.lang.String
	 */
	public java.lang.String getPk_pre_bill () {
		return pk_pre_bill;
	}
	
	/**
	 * 属性pk_pre_bill的Setter方法.属性名：最新生成单据主键
	 * 创建日期:
	 * @param newPk_pre_bill java.lang.String
	 */
	public void setPk_pre_bill (java.lang.String newPk_pre_bill ) {
	 	this.pk_pre_bill = newPk_pre_bill;
	} 	  

	/**
	 * 属性billmaker的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getBillmaker () {
		return billmaker;
	}

	/**
	 * 属性billmaker的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newBillmaker
	 *            java.lang.String
	 */
	public void setBillmaker(java.lang.String newBillmaker) {
		this.billmaker = newBillmaker;
	}

	/**
	 * 属性creationtime的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getBillmaketime() {
		return billmaketime;
	}

	/**
	 * 属性creationtime的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setBillmaketime(nc.vo.pub.lang.UFDateTime newBillmaketime) {
		this.billmaketime = newBillmaketime;
	}
	
	/**
	 * 属性creator的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCreator() {
		return creator;
	}

	/**
	 * 属性creator的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newCreator
	 *            java.lang.String
	 */
	public void setCreator(java.lang.String newCreator) {
		this.creator = newCreator;
	}

	/**
	 * 属性creationtime的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCreationtime() {
		return creationtime;
	}

	/**
	 * 属性creationtime的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newCreationtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
		this.creationtime = newCreationtime;
	}

	/**
	 * 属性modifier的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getModifier() {
		return modifier;
	}

	/**
	 * 属性modifier的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newModifier
	 *            java.lang.String
	 */
	public void setModifier(java.lang.String newModifier) {
		this.modifier = newModifier;
	}

	/**
	 * 属性modifiedtime的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getModifiedtime() {
		return modifiedtime;
	}

	/**
	 * 属性modifiedtime的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newModifiedtime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
		this.modifiedtime = newModifiedtime;
	}

	/**
	 * 属性auditor的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getAuditor() {
		return auditor;
	}

	/**
	 * 属性auditor的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAuditor
	 *            java.lang.String
	 */
	public void setAuditor(java.lang.String newAuditor) {
		this.auditor = newAuditor;
	}

	/**
	 * 属性audittime的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getAudittime() {
		return audittime;
	}

	/**
	 * 属性audittime的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newAudittime
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setAudittime(nc.vo.pub.lang.UFDateTime newAudittime) {
		this.audittime = newAudittime;
	}

	/**
	 * 属性check_opinion的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getCheck_opinion() {
		return check_opinion;
	}

	/**
	 * 属性check_opinion的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newCheck_opinion
	 *            java.lang.String
	 */
	public void setCheck_opinion(java.lang.String newCheck_opinion) {
		this.check_opinion = newCheck_opinion;
	}

	/**
	 * 属性def1的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef1() {
		return def1;
	}

	/**
	 * 属性def1的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef1
	 *            java.lang.String
	 */
	public void setDef1(java.lang.String newDef1) {
		this.def1 = newDef1;
	}

	/**
	 * 属性def2的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef2() {
		return def2;
	}

	/**
	 * 属性def2的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef2
	 *            java.lang.String
	 */
	public void setDef2(java.lang.String newDef2) {
		this.def2 = newDef2;
	}

	/**
	 * 属性def3的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef3() {
		return def3;
	}

	/**
	 * 属性def3的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef3
	 *            java.lang.String
	 */
	public void setDef3(java.lang.String newDef3) {
		this.def3 = newDef3;
	}

	/**
	 * 属性def4的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef4() {
		return def4;
	}

	/**
	 * 属性def4的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef4
	 *            java.lang.String
	 */
	public void setDef4(java.lang.String newDef4) {
		this.def4 = newDef4;
	}

	/**
	 * 属性def5的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef5() {
		return def5;
	}

	/**
	 * 属性def5的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef5
	 *            java.lang.String
	 */
	public void setDef5(java.lang.String newDef5) {
		this.def5 = newDef5;
	}

	/**
	 * 属性def6的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef6() {
		return def6;
	}

	/**
	 * 属性def6的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef6
	 *            java.lang.String
	 */
	public void setDef6(java.lang.String newDef6) {
		this.def6 = newDef6;
	}

	/**
	 * 属性def7的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef7() {
		return def7;
	}

	/**
	 * 属性def7的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef7
	 *            java.lang.String
	 */
	public void setDef7(java.lang.String newDef7) {
		this.def7 = newDef7;
	}

	/**
	 * 属性def8的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef8() {
		return def8;
	}

	/**
	 * 属性def8的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef8
	 *            java.lang.String
	 */
	public void setDef8(java.lang.String newDef8) {
		this.def8 = newDef8;
	}

	/**
	 * 属性def9的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef9() {
		return def9;
	}

	/**
	 * 属性def9的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef9
	 *            java.lang.String
	 */
	public void setDef9(java.lang.String newDef9) {
		this.def9 = newDef9;
	}

	/**
	 * 属性def10的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef10() {
		return def10;
	}

	/**
	 * 属性def10的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef10
	 *            java.lang.String
	 */
	public void setDef10(java.lang.String newDef10) {
		this.def10 = newDef10;
	}

	/**
	 * 属性def11的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef11() {
		return def11;
	}

	/**
	 * 属性def11的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef11
	 *            java.lang.String
	 */
	public void setDef11(java.lang.String newDef11) {
		this.def11 = newDef11;
	}

	/**
	 * 属性def12的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef12() {
		return def12;
	}

	/**
	 * 属性def12的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef12
	 *            java.lang.String
	 */
	public void setDef12(java.lang.String newDef12) {
		this.def12 = newDef12;
	}

	/**
	 * 属性def13的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef13() {
		return def13;
	}

	/**
	 * 属性def13的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef13
	 *            java.lang.String
	 */
	public void setDef13(java.lang.String newDef13) {
		this.def13 = newDef13;
	}

	/**
	 * 属性def14的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef14() {
		return def14;
	}

	/**
	 * 属性def14的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef14
	 *            java.lang.String
	 */
	public void setDef14(java.lang.String newDef14) {
		this.def14 = newDef14;
	}

	/**
	 * 属性def15的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef15() {
		return def15;
	}

	/**
	 * 属性def15的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef15
	 *            java.lang.String
	 */
	public void setDef15(java.lang.String newDef15) {
		this.def15 = newDef15;
	}

	/**
	 * 属性def16的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef16() {
		return def16;
	}

	/**
	 * 属性def16的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef16
	 *            java.lang.String
	 */
	public void setDef16(java.lang.String newDef16) {
		this.def16 = newDef16;
	}

	/**
	 * 属性def17的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef17() {
		return def17;
	}

	/**
	 * 属性def17的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef17
	 *            java.lang.String
	 */
	public void setDef17(java.lang.String newDef17) {
		this.def17 = newDef17;
	}

	/**
	 * 属性def18的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef18() {
		return def18;
	}

	/**
	 * 属性def18的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef18
	 *            java.lang.String
	 */
	public void setDef18(java.lang.String newDef18) {
		this.def18 = newDef18;
	}

	/**
	 * 属性def19的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef19() {
		return def19;
	}

	/**
	 * 属性def19的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef19
	 *            java.lang.String
	 */
	public void setDef19(java.lang.String newDef19) {
		this.def19 = newDef19;
	}

	/**
	 * 属性def20的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getDef20() {
		return def20;
	}

	/**
	 * 属性def20的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDef20
	 *            java.lang.String
	 */
	public void setDef20(java.lang.String newDef20) {
		this.def20 = newDef20;
	}

	/**
	 * 属性dr的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newDr
	 *            java.lang.Integer
	 */
	public void setDr(java.lang.Integer newDr) {
		this.dr = newDr;
	}

	/**
	 * 属性ts的Getter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法. 创建日期:2009-12-01 19:14:14
	 * 
	 * @param newTs
	 *            nc.vo.pub.lang.UFDateTime
	 */
	public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
		this.ts = newTs;
	}

	/**
	 * @return the pk_project
	 */
	public String getPk_project() {
		return pk_project;
	}

	/**
	 * @param pk_project
	 *            the pk_project to set
	 */
	public void setPk_project(String pk_project) {
		this.pk_project = pk_project;
	}

	/**
	 * @return the pk_wo_dept
	 */
	public java.lang.String getPk_wo_dept() {
		return pk_wo_dept;
	}

	/**
	 * @param pk_wo_dept
	 *            the pk_wo_dept to set
	 */
	public void setPk_wo_dept(java.lang.String pk_wo_dept) {
		this.pk_wo_dept = pk_wo_dept;
	}
	
	/**
	 * 属性pk_inspection_road的Getter方法.属性名：检修路线
	 * 创建日期:
	 * @return java.lang.String
	 */
	
	public java.lang.String getPk_inspection_road () {
		return pk_inspection_road;
	}   
	/**
	 * 属性pk_inspection_road的Setter方法.属性名：检修路线
	 * 创建日期:
	 * @param newPk_inspection_road java.lang.String
	 */
	public void setPk_inspection_road (java.lang.String newPk_inspection_road ) {
	 	this.pk_inspection_road = newPk_inspection_road;
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getParentPKFieldName() {
		return null;
	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getPKFieldName() {
		return "pk_pm";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2009-12-01 19:14:14
	 * 
	 * @return java.lang.String
	 */
	@Override
	public java.lang.String getTableName() {
		return "emm_pm";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2009-12-01 19:14:14
	 */
	public PMHeadVO() {
		super();
	}

	public UFDate getNext_create_date() {
		return next_create_date;
	}

	public void setNext_create_date(UFDate next_create_date) {
		this.next_create_date = next_create_date;
	}

	/**
	 * 属性pk_transitype的Getter方法. 创建日期:
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPk_transitype() {
		return pk_transitype;
	}

	/**
	 * 属性pk_transitype的Setter方法. 创建日期:
	 * 
	 * @param newPk_transitype
	 *            java.lang.String
	 */
	public void setPk_transitype(java.lang.String newPk_transitype) {
		this.pk_transitype = newPk_transitype;
	}

	public String getPk_wo_dept_v() {
		return pk_wo_dept_v;
	}

	public void setPk_wo_dept_v(String pk_wo_dept_v) {
		this.pk_wo_dept_v = pk_wo_dept_v;
	}
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "emm_pm";
	}    
}
