/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mmpub.setanalysis.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class SaOptionVO extends SuperVO {
    public static final String TABLENAME = "mm_saoption";

    public static final String PK_OPTION = "pk_option";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String PK_ORG_V = "pk_org_v";

    public static final String SINGLESET = "singleset";

    public static final String MULTISET = "multiset";

    public static final String STOCK = "stock";

    public static final String PO = "po";

    public static final String MPS = "mps";

    public static final String SCMPRAY = "scmpray";

    public static final String SCMPO = "scmpo";

    public static final String WWBILL = "wwbill";

    public static final String TRANSP = "transp";

    public static final String TRANSA = "transa";

    public static final String CREATOR = "creator";

    public static final String CREATIONTIME = "creationtime";

    public static final String FDEMANDTYPE = "fdemandtype";

    public static final String BDEPT = "bdept";

    public static final String DMO = "dmo";

    public static final String PMO = "pmo";

    public static final String HISTORYSUPPLYNUM = "historysupplynum";

    public static final String BENABLELOG = "benablelog";

    // //子件损耗-add by lizhk-V631新增-20130725
    public static final String ISDISSIPATION = "isdissipation";

    // 到货计划 V636
    public static final String DELIVERYSCHEDULE = "deliveryschedule";

    // 单据交易类型编码 V636 141107
    public static final String BILLTYPE = "billtype";
    
    public static final String VDEF1 = "vdef1";
    public static final String VDEF2 = "vdef2";

    public static final String VDEF3 = "vdef3";
    public static final String VDEF4 = "vdef4";
    public static final String VDEF5 = "vdef5";



    public String getVdef1() {
        return (java.lang.String) this.getAttributeValue("vdef1");
	}

	public void setVdef1(String vdef1) {
        this.setAttributeValue("vdef1", vdef1);
	}

	public String getVdef2() {
        return (java.lang.String) this.getAttributeValue("vdef2");
	}

	public void setVdef2(String vdef2) {
        this.setAttributeValue("vdef2", vdef2);
	}

	public String getVdef3() {
        return (java.lang.String) this.getAttributeValue("vdef3");
	}

	public void setVdef3(String vdef3) {
        this.setAttributeValue("vdef3", vdef3);
	}

	public String getVdef4() {
        return (java.lang.String) this.getAttributeValue("vdef4");
	}

	public void setVdef4(String vdef4) {
        this.setAttributeValue("vdef4", vdef4);
	}

	public String getVdef5() {
        return (java.lang.String) this.getAttributeValue("vdef5");
	}

	public void setVdef5(String vdef5) {
        this.setAttributeValue("vdef5", vdef5);
	}

	/**
     * 属性pk_option的Getter方法.属性名：分析选项主键
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_option() {
        return (java.lang.String) this.getAttributeValue("pk_option");
    }

    /**
     * 属性pk_option的Setter方法.属性名：分析选项主键
     * 创建日期:
     * 
     * @param newPk_option java.lang.String
     */
    public void setPk_option(java.lang.String newPk_option) {
        this.setAttributeValue("pk_option", newPk_option);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：工厂最新版本
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：工厂最新版本
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性pk_org_v的Getter方法.属性名：工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_v() {
        return (java.lang.String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 属性pk_org_v的Setter方法.属性名：工厂
     * 创建日期:
     * 
     * @param newPk_org_v java.lang.String
     */
    public void setPk_org_v(java.lang.String newPk_org_v) {
        this.setAttributeValue("pk_org_v", newPk_org_v);
    }

    /**
     * 属性singleset的Getter方法.属性名：单层齐套
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getSingleset() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("singleset");
    }

    /**
     * 属性singleset的Setter方法.属性名：单层齐套
     * 创建日期:
     * 
     * @param newSingleset nc.vo.pub.lang.UFBoolean
     */
    public void setSingleset(nc.vo.pub.lang.UFBoolean newSingleset) {
        this.setAttributeValue("singleset", newSingleset);
    }

    /**
     * 属性multiset的Getter方法.属性名：多层齐套
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getMultiset() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("multiset");
    }

    /**
     * 属性multiset的Setter方法.属性名：多层齐套
     * 创建日期:
     * 
     * @param newMultiset nc.vo.pub.lang.UFBoolean
     */
    public void setMultiset(nc.vo.pub.lang.UFBoolean newMultiset) {
        this.setAttributeValue("multiset", newMultiset);
    }

    /**
     * 属性stock的Getter方法.属性名：存量
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getStock() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("stock");
    }

    /**
     * 属性stock的Setter方法.属性名：存量
     * 创建日期:
     * 
     * @param newStock nc.vo.pub.lang.UFBoolean
     */
    public void setStock(nc.vo.pub.lang.UFBoolean newStock) {
        this.setAttributeValue("stock", newStock);
    }

    /**
     * 属性po的Getter方法.属性名：计划订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getPo() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("po");
    }

    /**
     * 属性po的Setter方法.属性名：计划订单
     * 创建日期:
     * 
     * @param newPo nc.vo.pub.lang.UFBoolean
     */
    public void setPo(nc.vo.pub.lang.UFBoolean newPo) {
        this.setAttributeValue("po", newPo);
    }

    /**
     * 属性mps的Getter方法.属性名：主生产计划
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getMps() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("mps");
    }

    /**
     * 属性mps的Setter方法.属性名：主生产计划
     * 创建日期:
     * 
     * @param newMps nc.vo.pub.lang.UFBoolean
     */
    public void setMps(nc.vo.pub.lang.UFBoolean newMps) {
        this.setAttributeValue("mps", newMps);
    }

    /**
     * 属性scmpray的Getter方法.属性名：请购单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getScmpray() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("scmpray");
    }

    /**
     * 属性scmpray的Setter方法.属性名：请购单
     * 创建日期:
     * 
     * @param newScmpray nc.vo.pub.lang.UFBoolean
     */
    public void setScmpray(nc.vo.pub.lang.UFBoolean newScmpray) {
        this.setAttributeValue("scmpray", newScmpray);
    }

    /**
     * 属性scmpo的Getter方法.属性名：采购订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getScmpo() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("scmpo");
    }

    /**
     * 属性scmpo的Setter方法.属性名：采购订单
     * 创建日期:
     * 
     * @param newScmpo nc.vo.pub.lang.UFBoolean
     */
    public void setScmpo(nc.vo.pub.lang.UFBoolean newScmpo) {
        this.setAttributeValue("scmpo", newScmpo);
    }

    /**
     * 属性wwbill的Getter方法.属性名：委外订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getWwbill() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("wwbill");
    }

    /**
     * 属性wwbill的Setter方法.属性名：委外订单
     * 创建日期:
     * 
     * @param newWwbill nc.vo.pub.lang.UFBoolean
     */
    public void setWwbill(nc.vo.pub.lang.UFBoolean newWwbill) {
        this.setAttributeValue("wwbill", newWwbill);
    }

    /**
     * 属性transp的Getter方法.属性名：调入申请
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getTransp() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("transp");
    }

    /**
     * 属性transp的Setter方法.属性名：调入申请
     * 创建日期:
     * 
     * @param newTransp nc.vo.pub.lang.UFBoolean
     */
    public void setTransp(nc.vo.pub.lang.UFBoolean newTransp) {
        this.setAttributeValue("transp", newTransp);
    }

    /**
     * 属性transa的Getter方法.属性名：调拨订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getTransa() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("transa");
    }

    /**
     * 属性transa的Setter方法.属性名：调拨订单
     * 创建日期:
     * 
     * @param newTransa nc.vo.pub.lang.UFBoolean
     */
    public void setTransa(nc.vo.pub.lang.UFBoolean newTransa) {
        this.setAttributeValue("transa", newTransa);
    }

    /**
     * 属性creator的Getter方法.属性名：创建人
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCreator() {
        return (java.lang.String) this.getAttributeValue("creator");
    }

    /**
     * 属性creator的Setter方法.属性名：创建人
     * 创建日期:
     * 
     * @param newCreator java.lang.String
     */
    public void setCreator(java.lang.String newCreator) {
        this.setAttributeValue("creator", newCreator);
    }

    /**
     * 属性creationtime的Getter方法.属性名：创建时间
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getCreationtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("creationtime");
    }

    /**
     * 属性creationtime的Setter方法.属性名：创建时间
     * 创建日期:
     * 
     * @param newCreationtime nc.vo.pub.lang.UFDateTime
     */
    public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
        this.setAttributeValue("creationtime", newCreationtime);
    }

    /**
     * 属性fdemandtype的Getter方法.属性名：需求类型
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getFdemandtype() {
        return (java.lang.Integer) this.getAttributeValue("fdemandtype");
    }

    /**
     * 属性fdemandtype的Setter方法.属性名：需求类型
     * 创建日期:
     * 
     * @param newFdemandtype java.lang.Integer
     */
    public void setFdemandtype(java.lang.Integer newFdemandtype) {
        this.setAttributeValue("fdemandtype", newFdemandtype);
    }

    /**
     * 属性bdept的Getter方法.属性名：部门
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBdept() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bdept");
    }

    /**
     * 属性bdept的Setter方法.属性名：部门
     * 创建日期:
     * 
     * @param newBdept nc.vo.pub.lang.UFBoolean
     */
    public void setBdept(nc.vo.pub.lang.UFBoolean newBdept) {
        this.setAttributeValue("bdept", newBdept);
    }

    /**
     * 属性dmo的Getter方法.属性名：离散生产订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getDmo() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("dmo");
    }

    /**
     * 属性dmo的Setter方法.属性名：离散生产订单
     * 创建日期:
     * 
     * @param newDmo nc.vo.pub.lang.UFBoolean
     */
    public void setDmo(nc.vo.pub.lang.UFBoolean newDmo) {
        this.setAttributeValue("dmo", newDmo);
    }

    /**
     * 属性pmo的Getter方法.属性名：流程生产订单
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getPmo() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("pmo");
    }

    /**
     * 属性pmo的Setter方法.属性名：流程生产订单
     * 创建日期:
     * 
     * @param newPmo nc.vo.pub.lang.UFBoolean
     */
    public void setPmo(nc.vo.pub.lang.UFBoolean newPmo) {
        this.setAttributeValue("pmo", newPmo);
    }

    /**
     * 属性historysupplynum的Getter方法.属性名：历史供给天数
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getHistorysupplynum() {
        return (java.lang.Integer) this.getAttributeValue("historysupplynum");
    }

    /**
     * 属性historysupplynum的Setter方法.属性名：历史供给天数
     * 创建日期:
     * 
     * @param newHistorysupplynum java.lang.Integer
     */
    public void setHistorysupplynum(java.lang.Integer newHistorysupplynum) {
        this.setAttributeValue("historysupplynum", newHistorysupplynum);
    }

    /**
     * 属性benablelog的Getter方法.属性名：启用日志
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBenablelog() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("benablelog");
    }

    /**
     * 属性benablelog的Setter方法.属性名：启用日志
     * 创建日期:
     * 
     * @param newBenablelog nc.vo.pub.lang.UFBoolean
     */
    public void setBenablelog(nc.vo.pub.lang.UFBoolean newBenablelog) {
        this.setAttributeValue("benablelog", newBenablelog);
    }

    /**
     * 属性deliveryschedule的Getter方法.属性名：到货计划
     * 创建日期:20131230
     * add by caijingc
     * v65新增
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getDeliverySchedule() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("deliveryschedule");
    }

    /**
     * 属性deliveryschedule的Setter方法.属性名：到货计划
     * 创建日期:20131230
     * add by caijingc
     * V65新增
     * 
     * @param newDeliverySchedule nc.vo.pub.lang.UFBoolean
     */
    public void setDeliverySchedule(nc.vo.pub.lang.UFBoolean newDeliverySchedule) {
        this.setAttributeValue("deliveryschedule", newDeliverySchedule);
    }

    /**
     * 属性isdissipation的Getter方法.属性名：子件损耗
     * 创建日期:20130725
     * add by lizhk
     * v631新增
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getIsdissipation() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("isdissipation");
    }

    /**
     * 属性isdissipation的Setter方法.属性名：子件损耗
     * 创建日期:20130725
     * add by lizhk
     * V631新增
     * 
     * @param isdissipation nc.vo.pub.lang.UFBoolean
     */
    public void setIsdissipation(nc.vo.pub.lang.UFBoolean isdissipation) {
        this.setAttributeValue("isdissipation", isdissipation);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性billtype的Getter方法.属性名：单据交易编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getBillType() {
        return (java.lang.String) this.getAttributeValue("billtype");
    }

    /**
     * 属性billtype的Setter方法.属性名：单据交易编码
     * 创建日期:
     * 
     * @param newPk_option java.lang.String
     */
    public void setBillType(java.lang.String newBilltype) {
        this.setAttributeValue("billtype", newBilltype);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "pk_option";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mm_saoption";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public SaOptionVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mmpub.setanalysis.entity.SaOptionVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mmpub.mm_saoption");
        return meta;
    }
}
