/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.bd.material.pf;

import nc.vo.pub.SuperVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MaterialPfVO extends SuperVO {
  private java.lang.String pk_material_pf;

  private java.lang.String pk_group;

  private java.lang.String pk_org;

  private java.lang.String billno;

  private java.lang.Integer targetorg;

  private java.lang.String pk_billtypecode = "10WL";

  private java.lang.String proposer;

  private nc.vo.pub.lang.UFDateTime proposetime;

  private java.lang.Integer billstatus = -1;

  private java.lang.String pk_targetorg;

  private java.lang.String materialcode;

  private java.lang.String materialname;

  private java.lang.String materialname2;

  private java.lang.String materialname3;

  private java.lang.String materialname4;

  private java.lang.String materialname5;

  private java.lang.String materialname6;

  private java.lang.String pk_marbasclass;

  private java.lang.String approver;

  private nc.vo.pub.lang.UFDateTime approvetime;

  private java.lang.String approvenote;

  private java.lang.String memo;

  private java.lang.Object material;

  private java.lang.Integer dataoriginflag = 0;

  private java.lang.String creator;

  private nc.vo.pub.lang.UFDateTime creationtime;

  private java.lang.String modifier;

  private nc.vo.pub.lang.UFDateTime modifiedtime;

  private java.lang.Integer dr = 0;

  private nc.vo.pub.lang.UFDateTime ts;

  private java.lang.String remark;

  /*自定义项1-10*/
  private java.lang.String def1;

  private java.lang.String def10;

  private java.lang.String def2;

  private java.lang.String def3;

  private java.lang.String def4;

  private java.lang.String def5;

  private java.lang.String def6;

  private java.lang.String def7;

  private java.lang.String def8;

  private java.lang.String def9;

  public static final String PK_MATERIAL_PF = "pk_material_pf";

  public static final String PK_GROUP = "pk_group";

  public static final String PK_ORG = "pk_org";

  public static final String BILLNO = "billno";

  public static final String TARGETORG = "targetorg";

  public static final String PK_BILLTYPECODE = "pk_billtypecode";

  public static final String PROPOSER = "proposer";

  public static final String PROPOSETIME = "proposetime";

  public static final String BILLSTATUS = "billstatus";

  public static final String PK_TARGETORG = "pk_targetorg";

  public static final String MATERIALCODE = "materialcode";

  public static final String MATERIALNAME = "materialname";

  public static final String MATERIALNAME2 = "materialname2";

  public static final String MATERIALNAME3 = "materialname3";

  public static final String MATERIALNAME4 = "materialname4";

  public static final String MATERIALNAME5 = "materialname5";

  public static final String MATERIALNAME6 = "materialname6";

  public static final String PK_MARBASCLASS = "pk_marbasclass";

  public static final String APPROVER = "approver";

  public static final String APPROVETIME = "approvetime";

  public static final String APPROVENOTE = "approvenote";

  public static final String MEMO = "memo";

  public static final String MATERIAL = "material";

  public static final String DATAORIGINFLAG = "dataoriginflag";

  public static final String CREATOR = "creator";

  public static final String CREATIONTIME = "creationtime";

  public static final String MODIFIER = "modifier";

  public static final String MODIFIEDTIME = "modifiedtime";

  public static final String REMARK = "remark";

  /* 自定义项1-10 */

  public static final String DEF1 = "def1";

  public static final String DEF2 = "def2";

  public static final String DEF3 = "def3";

  public static final String DEF4 = "def4";

  public static final String DEF5 = "def5";

  public static final String DEF6 = "def6";

  public static final String DEF7 = "def7";

  public static final String DEF8 = "def8";

  public static final String DEF9 = "def9";

  public static final String DEF10 = "def10";

  /**
   * 属性pk_material_pf的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_material_pf() {
    return pk_material_pf;
  }

  /**
   * 属性pk_material_pf的Setter方法.
   * 创建日期:
   * 
   * @param newPk_material_pf java.lang.String
   */
  public void setPk_material_pf(java.lang.String newPk_material_pf) {
    this.pk_material_pf = newPk_material_pf;
  }

  /**
   * 属性pk_group的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_group() {
    return pk_group;
  }

  /**
   * 属性pk_group的Setter方法.
   * 创建日期:
   * 
   * @param newPk_group java.lang.String
   */
  public void setPk_group(java.lang.String newPk_group) {
    this.pk_group = newPk_group;
  }

  /**
   * 属性pk_org的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_org() {
    return pk_org;
  }

  /**
   * 属性pk_org的Setter方法.
   * 创建日期:
   * 
   * @param newPk_org java.lang.String
   */
  public void setPk_org(java.lang.String newPk_org) {
    this.pk_org = newPk_org;
  }

  /**
   * 属性billno的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getBillno() {
    return billno;
  }

  /**
   * 属性billno的Setter方法.
   * 创建日期:
   * 
   * @param newBillno java.lang.String
   */
  public void setBillno(java.lang.String newBillno) {
    this.billno = newBillno;
  }

  /**
   * 属性targetorg的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.Integer
   */
  public java.lang.Integer getTargetorg() {
    return targetorg;
  }

  /**
   * 属性targetorg的Setter方法.
   * 创建日期:
   * 
   * @param newTargetorg java.lang.Integer
   */
  public void setTargetorg(java.lang.Integer newTargetorg) {
    this.targetorg = newTargetorg;
  }

  /**
   * 属性pk_billtypecode的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_billtypecode() {
    return pk_billtypecode;
  }

  /**
   * 属性pk_billtypecode的Setter方法.
   * 创建日期:
   * 
   * @param newPk_billtypecode java.lang.String
   */
  public void setPk_billtypecode(java.lang.String newPk_billtypecode) {
    this.pk_billtypecode = newPk_billtypecode;
  }

  /**
   * 属性proposer的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getProposer() {
    return proposer;
  }

  /**
   * 属性proposer的Setter方法.
   * 创建日期:
   * 
   * @param newProposer java.lang.String
   */
  public void setProposer(java.lang.String newProposer) {
    this.proposer = newProposer;
  }

  /**
   * 属性proposetime的Getter方法.
   * 创建日期:
   * 
   * @return nc.vo.pub.lang.UFDateTime
   */
  public nc.vo.pub.lang.UFDateTime getProposetime() {
    return proposetime;
  }

  /**
   * 属性proposetime的Setter方法.
   * 创建日期:
   * 
   * @param newProposetime nc.vo.pub.lang.UFDateTime
   */
  public void setProposetime(nc.vo.pub.lang.UFDateTime newProposetime) {
    this.proposetime = newProposetime;
  }

  /**
   * 属性billstatus的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.Integer
   */
  public java.lang.Integer getBillstatus() {
    return billstatus;
  }

  /**
   * 属性billstatus的Setter方法.
   * 创建日期:
   * 
   * @param newBillstatus java.lang.Integer
   */
  public void setBillstatus(java.lang.Integer newBillstatus) {
    this.billstatus = newBillstatus;
  }

  /**
   * 属性pk_targetorg的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_targetorg() {
    return pk_targetorg;
  }

  /**
   * 属性pk_targetorg的Setter方法.
   * 创建日期:
   * 
   * @param newPk_targetorg java.lang.String
   */
  public void setPk_targetorg(java.lang.String newPk_targetorg) {
    this.pk_targetorg = newPk_targetorg;
  }

  /**
   * 属性materialcode的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialcode() {
    return materialcode;
  }

  /**
   * 属性materialcode的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialcode java.lang.String
   */
  public void setMaterialcode(java.lang.String newMaterialcode) {
    this.materialcode = newMaterialcode;
  }

  /**
   * 属性materialname的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname() {
    return materialname;
  }

  /**
   * 属性materialname的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname java.lang.String
   */
  public void setMaterialname(java.lang.String newMaterialname) {
    this.materialname = newMaterialname;
  }

  /**
   * 属性materialname2的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname2() {
    return materialname2;
  }

  /**
   * 属性materialname2的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname2 java.lang.String
   */
  public void setMaterialname2(java.lang.String newMaterialname2) {
    this.materialname2 = newMaterialname2;
  }

  /**
   * 属性materialname3的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname3() {
    return materialname3;
  }

  /**
   * 属性materialname3的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname3 java.lang.String
   */
  public void setMaterialname3(java.lang.String newMaterialname3) {
    this.materialname3 = newMaterialname3;
  }

  /**
   * 属性materialname4的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname4() {
    return materialname4;
  }

  /**
   * 属性materialname4的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname4 java.lang.String
   */
  public void setMaterialname4(java.lang.String newMaterialname4) {
    this.materialname4 = newMaterialname4;
  }

  /**
   * 属性materialname5的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname5() {
    return materialname5;
  }

  /**
   * 属性materialname5的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname5 java.lang.String
   */
  public void setMaterialname5(java.lang.String newMaterialname5) {
    this.materialname5 = newMaterialname5;
  }

  /**
   * 属性materialname6的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMaterialname6() {
    return materialname6;
  }

  /**
   * 属性materialname6的Setter方法.
   * 创建日期:
   * 
   * @param newMaterialname6 java.lang.String
   */
  public void setMaterialname6(java.lang.String newMaterialname6) {
    this.materialname6 = newMaterialname6;
  }

  /**
   * 属性pk_marbasclass的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPk_marbasclass() {
    return pk_marbasclass;
  }

  /**
   * 属性pk_marbasclass的Setter方法.
   * 创建日期:
   * 
   * @param newPk_marbasclass java.lang.String
   */
  public void setPk_marbasclass(java.lang.String newPk_marbasclass) {
    this.pk_marbasclass = newPk_marbasclass;
  }

  /**
   * 属性approver的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getApprover() {
    return approver;
  }

  /**
   * 属性approver的Setter方法.
   * 创建日期:
   * 
   * @param newApprover java.lang.String
   */
  public void setApprover(java.lang.String newApprover) {
    this.approver = newApprover;
  }

  /**
   * 属性approvetime的Getter方法.
   * 创建日期:
   * 
   * @return nc.vo.pub.lang.UFDateTime
   */
  public nc.vo.pub.lang.UFDateTime getApprovetime() {
    return approvetime;
  }

  /**
   * 属性approvetime的Setter方法.
   * 创建日期:
   * 
   * @param newApprovetime nc.vo.pub.lang.UFDateTime
   */
  public void setApprovetime(nc.vo.pub.lang.UFDateTime newApprovetime) {
    this.approvetime = newApprovetime;
  }

  /**
   * 属性approvenote的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getApprovenote() {
    return approvenote;
  }

  /**
   * 属性approvenote的Setter方法.
   * 创建日期:
   * 
   * @param newApprovenote java.lang.String
   */
  public void setApprovenote(java.lang.String newApprovenote) {
    this.approvenote = newApprovenote;
  }

  /**
   * 属性memo的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getMemo() {
    return memo;
  }

  /**
   * 属性memo的Setter方法.
   * 创建日期:
   * 
   * @param newMemo java.lang.String
   */
  public void setMemo(java.lang.String newMemo) {
    this.memo = newMemo;
  }

  /**
   * 属性material的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.Object
   */
  public java.lang.Object getMaterial() {
    return material;
  }

  /**
   * 属性material的Setter方法.
   * 创建日期:
   * 
   * @param newMaterial java.lang.Object
   */
  public void setMaterial(java.lang.Object newMaterial) {
    this.material = newMaterial;
  }

  /**
   * 属性dataoriginflag的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.Integer
   */
  public java.lang.Integer getDataoriginflag() {
    return dataoriginflag;
  }

  /**
   * 属性dataoriginflag的Setter方法.
   * 创建日期:
   * 
   * @param newDataoriginflag java.lang.Integer
   */
  public void setDataoriginflag(java.lang.Integer newDataoriginflag) {
    this.dataoriginflag = newDataoriginflag;
  }

  /**
   * 属性creator的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getCreator() {
    return creator;
  }

  /**
   * 属性creator的Setter方法.
   * 创建日期:
   * 
   * @param newCreator java.lang.String
   */
  public void setCreator(java.lang.String newCreator) {
    this.creator = newCreator;
  }

  /**
   * 属性creationtime的Getter方法.
   * 创建日期:
   * 
   * @return nc.vo.pub.lang.UFDateTime
   */
  public nc.vo.pub.lang.UFDateTime getCreationtime() {
    return creationtime;
  }

  /**
   * 属性creationtime的Setter方法.
   * 创建日期:
   * 
   * @param newCreationtime nc.vo.pub.lang.UFDateTime
   */
  public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
    this.creationtime = newCreationtime;
  }

  /**
   * 属性modifier的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getModifier() {
    return modifier;
  }

  /**
   * 属性modifier的Setter方法.
   * 创建日期:
   * 
   * @param newModifier java.lang.String
   */
  public void setModifier(java.lang.String newModifier) {
    this.modifier = newModifier;
  }

  /**
   * 属性modifiedtime的Getter方法.
   * 创建日期:
   * 
   * @return nc.vo.pub.lang.UFDateTime
   */
  public nc.vo.pub.lang.UFDateTime getModifiedtime() {
    return modifiedtime;
  }

  /**
   * 属性modifiedtime的Setter方法.
   * 创建日期:
   * 
   * @param newModifiedtime nc.vo.pub.lang.UFDateTime
   */
  public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
    this.modifiedtime = newModifiedtime;
  }

  /**
   * 属性dr的Getter方法.
   * 创建日期:
   * 
   * @return java.lang.Integer
   */
  public java.lang.Integer getDr() {
    return dr;
  }

  /**
   * 属性dr的Setter方法.
   * 创建日期:
   * 
   * @param newDr java.lang.Integer
   */
  public void setDr(java.lang.Integer newDr) {
    this.dr = newDr;
  }

  /**
   * 属性ts的Getter方法.
   * 创建日期:
   * 
   * @return nc.vo.pub.lang.UFDateTime
   */
  public nc.vo.pub.lang.UFDateTime getTs() {
    return ts;
  }

  /**
   * 属性ts的Setter方法.
   * 创建日期:
   * 
   * @param newTs nc.vo.pub.lang.UFDateTime
   */
  public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
    this.ts = newTs;
  }

  /**
   * <p>取得父VO主键字段.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getParentPKFieldName() {
    return null;
  }

  /**
   * <p>取得表主键.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getPKFieldName() {
    return "pk_material_pf";
  }

  /**
   * <p>返回表名称.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public java.lang.String getTableName() {
    return "bd_material_pf";
  }

  /**
   * <p>返回表名称.
   * <p>
   * 创建日期:
   * 
   * @return java.lang.String
   */
  public static java.lang.String getDefaultTableName() {
    return "bd_material_pf";
  }

  /**
   * 按照默认方式创建构造子.
   * 
   * 创建日期:
   */
  public MaterialPfVO() {
    super();
  }

  @Override
  @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.bd.material.pf.MaterialPfVO")
  public nc.vo.pub.IVOMeta getMetaData() {
    return nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory.getInstance().getVOMeta(
        "uap.material_pf");
  }

  public java.lang.String getDef1() {
    return def1;
  }

  public void setDef1(java.lang.String def1) {
    this.def1 = def1;
  }

  public java.lang.String getDef10() {
    return def10;
  }

  public void setDef10(java.lang.String def10) {
    this.def10 = def10;
  }

  public java.lang.String getDef2() {
    return def2;
  }

  public void setDef2(java.lang.String def2) {
    this.def2 = def2;
  }

  public java.lang.String getDef3() {
    return def3;
  }

  public void setDef3(java.lang.String def3) {
    this.def3 = def3;
  }

  public java.lang.String getDef4() {
    return def4;
  }

  public void setDef4(java.lang.String def4) {
    this.def4 = def4;
  }

  public java.lang.String getDef5() {
    return def5;
  }

  public void setDef5(java.lang.String def5) {
    this.def5 = def5;
  }

  public java.lang.String getDef6() {
    return def6;
  }

  public void setDef6(java.lang.String def6) {
    this.def6 = def6;
  }

  public java.lang.String getDef7() {
    return def7;
  }

  public void setDef7(java.lang.String def7) {
    this.def7 = def7;
  }

  public java.lang.String getDef8() {
    return def8;
  }

  public void setDef8(java.lang.String def8) {
    this.def8 = def8;
  }

  public java.lang.String getDef9() {
    return def9;
  }

  public void setDef9(java.lang.String def9) {
    this.def9 = def9;
  }

  public java.lang.String getRemark() {
    return this.remark;
  }

  public void setRemark(java.lang.String remark) {
    this.remark = remark;
  }
}
